#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_presets.h"
#include "special_presets.h"
#include "textures.h"

#include "make_const_nonconst.h"
#include "levels/vcutm/texture.inc.c"
#include "levels/vcutm/areas/1/1/model.inc.c"
#include "levels/vcutm/areas/1/2/model.inc.c"
#include "levels/vcutm/areas/1/3/model.inc.c"
#include "levels/vcutm/areas/1/4/model.inc.c"
#include "levels/vcutm/seesaw/model.inc.c"
#include "levels/vcutm/areas/1/collision.inc.c"
#include "levels/vcutm/areas/1/macro.inc.c"
#include "levels/vcutm/seesaw/collision.inc.c"

#include "levels/vcutm/leveldata.inc.c"

#include "levels/vcutm/carousel/model.inc.c"
#include "levels/vcutm/carousel/collision.inc.c"
#include "levels/vcutm/jack/model.inc.c"
#include "levels/vcutm/jack/anims/data.inc.c"
#include "levels/vcutm/jack/anims/table.inc.c"
#include "levels/vcutm/kitten_layla/model.inc.c"
#include "levels/vcutm/kitten_layla/anims/data.inc.c"
#include "levels/vcutm/kitten_layla/anims/table.inc.c"
#include "levels/vcutm/sweet/model.inc.c"
#include "levels/vcutm/sweet/anims/data.inc.c"
#include "levels/vcutm/sweet/anims/table.inc.c"
#include "levels/vcutm/hocus/model.inc.c"
#include "levels/vcutm/hocus/anims/data.inc.c"
#include "levels/vcutm/hocus/anims/table.inc.c"