#include "src/game/envfx_snow.h"

const GeoLayout peach_mark_001_switch_opt1_000_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_mark_000_displaylist_mesh_layer_1_mat_override_eye_open_f3d_f3d_v4_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_mark_001_switch_opt1_000_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_mark_000_displaylist_mesh_layer_1_mat_override_face_halfopen_v4_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_mark_001_switch_opt1_000_switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_mark_000_displaylist_mesh_layer_1_mat_override_face_closed_v4_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_mark_001_switch_opt1_000_switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_mark_000_displaylist_mesh_layer_1_mat_override_face_surprised_v4_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_mark_001_switch_opt1_000_switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_mark_000_displaylist_mesh_layer_1_mat_override_eye_open_f3d_f3d_v4_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_mark_001_switch_opt1_000_switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_mark_000_displaylist_mesh_layer_1_mat_override_face_halfopen_v4_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_mark_001_switch_opt1_000_switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_mark_000_displaylist_mesh_layer_1_mat_override_face_closed_v4_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_mark_001_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_mark_000_offset_001_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, peach_mark_000_offset_002_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_SWITCH_CASE(8, geo_switch_peach_eyes),
							GEO_OPEN_NODE(),
								GEO_NODE_START(),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_mark_000_displaylist_mesh_layer_1),
								GEO_CLOSE_NODE(),
								GEO_BRANCH(1, peach_mark_001_switch_opt1_000_switch_opt1),
								GEO_BRANCH(1, peach_mark_001_switch_opt1_000_switch_opt2),
								GEO_BRANCH(1, peach_mark_001_switch_opt1_000_switch_opt3),
								GEO_BRANCH(1, peach_mark_001_switch_opt1_000_switch_opt4),
								GEO_BRANCH(1, peach_mark_001_switch_opt1_000_switch_opt5),
								GEO_BRANCH(1, peach_mark_001_switch_opt1_000_switch_opt6),
								GEO_BRANCH(1, peach_mark_001_switch_opt1_000_switch_opt7),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 38, -78, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 0, 0, NULL),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 0, 0, NULL),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, 84, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_mark_000_offset_005_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 104, 0, 0, peach_mark_000_offset_006_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, peach_mark_000_offset_007_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_mark_002_offset_002_mesh_layer_1),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, -84, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_mark_000_offset_008_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 104, 0, 0, peach_mark_000_offset_009_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, peach_mark_000_offset_010_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_mark_002_offset_003_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, NULL),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -23, -1, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_mark_000_offset_011_mesh_layer_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_mark_001_switch_opt0_000_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_mark_000_displaylist_mesh_layer_1_mat_override_eye_open_f3d_f3d_v4_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_mark_001_switch_opt0_000_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_mark_000_displaylist_mesh_layer_1_mat_override_face_halfopen_v4_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_mark_001_switch_opt0_000_switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_mark_000_displaylist_mesh_layer_1_mat_override_face_closed_v4_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_mark_001_switch_opt0_000_switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_mark_000_displaylist_mesh_layer_1_mat_override_face_surprised_v4_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_mark_001_switch_opt0_000_switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_mark_000_displaylist_mesh_layer_1_mat_override_eye_open_f3d_f3d_v4_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_mark_001_switch_opt0_000_switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_mark_000_displaylist_mesh_layer_1_mat_override_face_halfopen_v4_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_mark_001_switch_opt0_000_switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_mark_000_displaylist_mesh_layer_1_mat_override_face_closed_v4_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_mark_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(10, geo_update_layer_transparency),
				GEO_SWITCH_CASE(2, geo_switch_anim_state),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_mark_000_offset_001_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, peach_mark_000_offset_002_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(8, geo_switch_peach_eyes),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_mark_000_displaylist_mesh_layer_1),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, peach_mark_001_switch_opt0_000_switch_opt1),
												GEO_BRANCH(1, peach_mark_001_switch_opt0_000_switch_opt2),
												GEO_BRANCH(1, peach_mark_001_switch_opt0_000_switch_opt3),
												GEO_BRANCH(1, peach_mark_001_switch_opt0_000_switch_opt4),
												GEO_BRANCH(1, peach_mark_001_switch_opt0_000_switch_opt5),
												GEO_BRANCH(1, peach_mark_001_switch_opt0_000_switch_opt6),
												GEO_BRANCH(1, peach_mark_001_switch_opt0_000_switch_opt7),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 38, -78, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 0, 0, NULL),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 0, 0, NULL),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, 84, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_mark_000_offset_005_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 104, 0, 0, peach_mark_000_offset_006_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, peach_mark_000_offset_007_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_mark_002_offset_002_mesh_layer_1),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, -84, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_mark_000_offset_008_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 104, 0, 0, peach_mark_000_offset_009_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, peach_mark_000_offset_010_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_mark_002_offset_003_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, NULL),
									GEO_ANIMATED_PART(LAYER_OPAQUE, -23, -1, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_mark_000_offset_011_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, peach_mark_001_switch_opt1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_mark_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_mark_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
