extern const GeoLayout peach_mark_001_switch_opt1_000_switch_opt1[];
extern const GeoLayout peach_mark_001_switch_opt1_000_switch_opt2[];
extern const GeoLayout peach_mark_001_switch_opt1_000_switch_opt3[];
extern const GeoLayout peach_mark_001_switch_opt1_000_switch_opt4[];
extern const GeoLayout peach_mark_001_switch_opt1_000_switch_opt5[];
extern const GeoLayout peach_mark_001_switch_opt1_000_switch_opt6[];
extern const GeoLayout peach_mark_001_switch_opt1_000_switch_opt7[];
extern const GeoLayout peach_mark_001_switch_opt1[];
extern const GeoLayout peach_mark_001_switch_opt0_000_switch_opt1[];
extern const GeoLayout peach_mark_001_switch_opt0_000_switch_opt2[];
extern const GeoLayout peach_mark_001_switch_opt0_000_switch_opt3[];
extern const GeoLayout peach_mark_001_switch_opt0_000_switch_opt4[];
extern const GeoLayout peach_mark_001_switch_opt0_000_switch_opt5[];
extern const GeoLayout peach_mark_001_switch_opt0_000_switch_opt6[];
extern const GeoLayout peach_mark_001_switch_opt0_000_switch_opt7[];
extern const GeoLayout peach_mark_geo[];
extern Lights1 peach_mark_m_colors_f3d_f3d_v4_lights;
extern Lights1 peach_mark_tail_f3d_f3d_v4_lights;
extern Lights1 peach_mark_jewel_f3d_v4_lights;
extern Lights1 peach_mark_crown_base_f3d_v4_lights;
extern Lights1 peach_mark_crown_jewel_f3d_v4_lights;
extern Lights1 peach_mark_eye_open_f3d_f3d_v4_lights;
extern Lights1 peach_mark_ears_f3d_f3d_v4_lights;
extern Lights1 peach_mark_mouth_lights;
extern Lights1 peach_mark_face_halfopen_v4_lights;
extern Lights1 peach_mark_face_closed_v4_lights;
extern Lights1 peach_mark_face_surprised_v4_lights;
extern Lights1 peach_mark_dress_f3d_v4_lights;
extern u8 peach_mark_m_colors_ci4[];
extern u8 peach_mark_m_colors_ci4_pal_rgba16[];
extern u8 peach_mark_m_tail_ci4[];
extern u8 peach_mark_m_tail_ci4_pal_rgba16[];
extern u8 peach_mark_v_chest_ci8[];
extern u8 peach_mark_v_chest_ci8_pal_rgba16[];
extern u8 peach_mark_v_crown_ci8[];
extern u8 peach_mark_v_crown_ci8_pal_rgba16[];
extern u8 peach_mark_eyes_open_ci4[];
extern u8 peach_mark_eyes_open_ci4_pal_rgba16[];
extern u8 peach_mark_ears_ci4[];
extern u8 peach_mark_ears_ci4_pal_rgba16[];
extern u8 peach_mark_cream_mouth_i8[];
extern u8 peach_mark_eyes_halfopen_ci4[];
extern u8 peach_mark_eyes_halfopen_ci4_pal_rgba16[];
extern u8 peach_mark_eyes_closed_ci4[];
extern u8 peach_mark_eyes_closed_ci4_pal_rgba16[];
extern u8 peach_mark_eyes_surprised_ci8[];
extern u8 peach_mark_eyes_surprised_ci8_pal_rgba16[];
extern u8 peach_mark_m_dress_ci4[];
extern u8 peach_mark_m_dress_ci4_pal_rgba16[];
extern Vtx peach_mark_000_offset_001_mesh_layer_1_vtx_0[80];
extern Gfx peach_mark_000_offset_001_mesh_layer_1_tri_0[];
extern Vtx peach_mark_000_offset_001_mesh_layer_1_vtx_1[16];
extern Gfx peach_mark_000_offset_001_mesh_layer_1_tri_1[];
extern Vtx peach_mark_000_offset_002_mesh_layer_1_vtx_0[152];
extern Gfx peach_mark_000_offset_002_mesh_layer_1_tri_0[];
extern Vtx peach_mark_000_offset_002_mesh_layer_1_vtx_1[9];
extern Gfx peach_mark_000_offset_002_mesh_layer_1_tri_1[];
extern Vtx peach_mark_000_displaylist_mesh_layer_1_vtx_0[41];
extern Gfx peach_mark_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx peach_mark_000_displaylist_mesh_layer_1_vtx_1[16];
extern Gfx peach_mark_000_displaylist_mesh_layer_1_tri_1[];
extern Vtx peach_mark_000_displaylist_mesh_layer_1_vtx_2[234];
extern Gfx peach_mark_000_displaylist_mesh_layer_1_tri_2[];
extern Vtx peach_mark_000_displaylist_mesh_layer_1_vtx_3[8];
extern Gfx peach_mark_000_displaylist_mesh_layer_1_tri_3[];
extern Vtx peach_mark_000_displaylist_mesh_layer_1_vtx_4[12];
extern Gfx peach_mark_000_displaylist_mesh_layer_1_tri_4[];
extern Vtx peach_mark_000_displaylist_mesh_layer_1_vtx_5[6];
extern Gfx peach_mark_000_displaylist_mesh_layer_1_tri_5[];
extern Vtx peach_mark_000_offset_005_mesh_layer_1_vtx_0[95];
extern Gfx peach_mark_000_offset_005_mesh_layer_1_tri_0[];
extern Vtx peach_mark_000_offset_006_mesh_layer_1_vtx_0[72];
extern Gfx peach_mark_000_offset_006_mesh_layer_1_tri_0[];
extern Vtx peach_mark_000_offset_007_mesh_layer_1_vtx_0[35];
extern Gfx peach_mark_000_offset_007_mesh_layer_1_tri_0[];
extern Vtx peach_mark_002_offset_002_mesh_layer_1_vtx_0[31];
extern Gfx peach_mark_002_offset_002_mesh_layer_1_tri_0[];
extern Vtx peach_mark_000_offset_008_mesh_layer_1_vtx_0[95];
extern Gfx peach_mark_000_offset_008_mesh_layer_1_tri_0[];
extern Vtx peach_mark_000_offset_009_mesh_layer_1_vtx_0[73];
extern Gfx peach_mark_000_offset_009_mesh_layer_1_tri_0[];
extern Vtx peach_mark_000_offset_010_mesh_layer_1_vtx_0[41];
extern Gfx peach_mark_000_offset_010_mesh_layer_1_tri_0[];
extern Vtx peach_mark_002_offset_003_mesh_layer_1_vtx_0[31];
extern Gfx peach_mark_002_offset_003_mesh_layer_1_tri_0[];
extern Vtx peach_mark_000_offset_011_mesh_layer_1_vtx_0[63];
extern Gfx peach_mark_000_offset_011_mesh_layer_1_tri_0[];
extern Vtx peach_mark_000_offset_011_mesh_layer_1_vtx_1[54];
extern Gfx peach_mark_000_offset_011_mesh_layer_1_tri_1[];
extern Gfx mat_peach_mark_m_colors_f3d_f3d_v4[];
extern Gfx mat_revert_peach_mark_m_colors_f3d_f3d_v4[];
extern Gfx mat_peach_mark_tail_f3d_f3d_v4[];
extern Gfx mat_revert_peach_mark_tail_f3d_f3d_v4[];
extern Gfx mat_peach_mark_jewel_f3d_v4[];
extern Gfx mat_revert_peach_mark_jewel_f3d_v4[];
extern Gfx mat_peach_mark_crown_base_f3d_v4[];
extern Gfx mat_peach_mark_crown_jewel_f3d_v4[];
extern Gfx mat_revert_peach_mark_crown_jewel_f3d_v4[];
extern Gfx mat_peach_mark_eye_open_f3d_f3d_v4[];
extern Gfx mat_revert_peach_mark_eye_open_f3d_f3d_v4[];
extern Gfx mat_peach_mark_ears_f3d_f3d_v4[];
extern Gfx mat_revert_peach_mark_ears_f3d_f3d_v4[];
extern Gfx mat_peach_mark_mouth[];
extern Gfx mat_peach_mark_face_halfopen_v4[];
extern Gfx mat_revert_peach_mark_face_halfopen_v4[];
extern Gfx mat_peach_mark_face_closed_v4[];
extern Gfx mat_revert_peach_mark_face_closed_v4[];
extern Gfx mat_peach_mark_face_surprised_v4[];
extern Gfx mat_revert_peach_mark_face_surprised_v4[];
extern Gfx mat_peach_mark_dress_f3d_v4[];
extern Gfx mat_revert_peach_mark_dress_f3d_v4[];
extern Gfx peach_mark_000_offset_001_mesh_layer_1[];
extern Gfx peach_mark_000_offset_002_mesh_layer_1[];
extern Gfx peach_mark_000_displaylist_mesh_layer_1[];
extern Gfx peach_mark_000_displaylist_mesh_layer_1_mat_override_eye_open_f3d_f3d_v4_0[];
extern Gfx peach_mark_000_displaylist_mesh_layer_1_mat_override_face_halfopen_v4_1[];
extern Gfx peach_mark_000_displaylist_mesh_layer_1_mat_override_face_closed_v4_2[];
extern Gfx peach_mark_000_displaylist_mesh_layer_1_mat_override_face_surprised_v4_3[];
extern Gfx peach_mark_000_offset_005_mesh_layer_1[];
extern Gfx peach_mark_000_offset_006_mesh_layer_1[];
extern Gfx peach_mark_000_offset_007_mesh_layer_1[];
extern Gfx peach_mark_002_offset_002_mesh_layer_1[];
extern Gfx peach_mark_000_offset_008_mesh_layer_1[];
extern Gfx peach_mark_000_offset_009_mesh_layer_1[];
extern Gfx peach_mark_000_offset_010_mesh_layer_1[];
extern Gfx peach_mark_002_offset_003_mesh_layer_1[];
extern Gfx peach_mark_000_offset_011_mesh_layer_1[];
extern Gfx peach_mark_material_revert_render_settings[];
