extern const GeoLayout transparent_star_geo[];
extern Lights2 transparent_star_sm64_material_004_lights;
extern Vtx transparent_star_000_displaylist_mesh_layer_5_vtx_0[201];
extern Gfx transparent_star_000_displaylist_mesh_layer_5_tri_0[];
extern Gfx mat_transparent_star_sm64_material_004[];
extern Gfx mat_revert_transparent_star_sm64_material_004[];
extern Gfx transparent_star_000_displaylist_mesh_layer_5[];
extern Gfx transparent_star_material_revert_render_settings[];
