#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_presets.h"
#include "special_presets.h"
#include "textures.h"

#include "make_const_nonconst.h"
#include "levels/sa/texture.inc.c"
#include "levels/sa/areas/1/1/model.inc.c"
#include "levels/sa/areas/1/2/model.inc.c"
#include "levels/sa/areas/1/collision.inc.c"
#include "levels/sa/areas/1/macro.inc.c"

#include "levels/sa/areas/area_2/texture_include.inc.c"
#include "levels/sa/areas/area_2/collision.inc.c"
#include "levels/sa/areas/area_2/macro.inc.c"
#include "levels/sa/areas/area_2/spline.inc.c"
#include "levels/sa/areas/area_2/model.inc.c"

#include "levels/sa/areas/area_3/collision.inc.c"
#include "levels/sa/areas/area_3/macro.inc.c"
#include "levels/sa/areas/area_3/spline.inc.c"

#include "levels/sa/gardevoir/model.inc.c"
#include "levels/sa/gardevoir/anims/data.inc.c"
#include "levels/sa/gardevoir/anims/table.inc.c"
#include "levels/sa/pocky/model.inc.c"
#include "levels/sa/pocky/anims/data.inc.c"
#include "levels/sa/pocky/anims/table.inc.c"
#include "levels/sa/ms_tree/model.inc.c"
#include "levels/sa/sorbet/model.inc.c"
#include "levels/sa/sorbet/anims/data.inc.c"
#include "levels/sa/sorbet/anims/table.inc.c"
#include "levels/sa/gremlin/model.inc.c"
#include "levels/sa/gremlin/anims/data.inc.c"
#include "levels/sa/gremlin/anims/table.inc.c"
#include "levels/sa/kz_nekoarc/model.inc.c"
#include "levels/sa/kz_nekoarc/anims/data.inc.c"
#include "levels/sa/kz_nekoarc/anims/table.inc.c"
#include "levels/sa/simple/model.inc.c"
#include "levels/sa/simple/anims/data.inc.c"
#include "levels/sa/simple/anims/table.inc.c"