#include "src/game/envfx_snow.h"

const GeoLayout goomba_crem_Root_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, goomba_crem_Root_mesh_layer_1_mat_override_eyeball_blink_0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 38, 0, goomba_crem_Head_mesh_layer_1_mat_override_eyeball_blink_0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 3, 13, 0, goomba_crem_lArm_001_mesh_layer_1_mat_override_eyeball_blink_0),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_crem_lArm_002_skinned_mesh_layer_1_mat_override_eyeball_blink_0),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 2, 20, 0, goomba_crem_lArm_002_mesh_layer_1_mat_override_eyeball_blink_0),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -4, 13, 0, goomba_crem_rArm_001_mesh_layer_1_mat_override_eyeball_blink_0),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_crem_rArm_002_skinned_mesh_layer_1_mat_override_eyeball_blink_0),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -1, 20, 0, goomba_crem_rArm_002_mesh_layer_1_mat_override_eyeball_blink_0),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 33, 0, 0, goomba_crem_lLeg_001_mesh_layer_1_mat_override_eyeball_blink_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_crem_lLeg_002_skinned_mesh_layer_1_mat_override_eyeball_blink_0),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 39, -1, 0, goomba_crem_lLeg_002_mesh_layer_1_mat_override_eyeball_blink_0),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_crem_lLeg_003_skinned_mesh_layer_1_mat_override_eyeball_blink_0),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 34, 1, 0, goomba_crem_lLeg_003_mesh_layer_1_mat_override_eyeball_blink_0),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, -33, 0, 0, goomba_crem_rLeg_001_mesh_layer_1_mat_override_eyeball_blink_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_crem_rLeg_002_skinned_mesh_layer_1_mat_override_eyeball_blink_0),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -39, 0, 0, goomba_crem_rLeg_002_mesh_layer_1_mat_override_eyeball_blink_0),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_crem_rLeg_003_skinned_mesh_layer_1_mat_override_eyeball_blink_0),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -34, 0, 0, goomba_crem_rLeg_003_mesh_layer_1_mat_override_eyeball_blink_0),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout goomba_crem_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(2, geo_switch_anim_state),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, goomba_crem_Root_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 38, 0, goomba_crem_Head_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 3, 13, 0, goomba_crem_lArm_001_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_crem_lArm_002_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 2, 20, 0, goomba_crem_lArm_002_mesh_layer_1),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -4, 13, 0, goomba_crem_rArm_001_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_crem_rArm_002_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -1, 20, 0, goomba_crem_rArm_002_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 33, 0, 0, goomba_crem_lLeg_001_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_crem_lLeg_002_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 39, -1, 0, goomba_crem_lLeg_002_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_crem_lLeg_003_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 34, 1, 0, goomba_crem_lLeg_003_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -33, 0, 0, goomba_crem_rLeg_001_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_crem_rLeg_002_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -39, 0, 0, goomba_crem_rLeg_002_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_crem_rLeg_003_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -34, 0, 0, goomba_crem_rLeg_003_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, goomba_crem_Root_Switch_opt1),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, goomba_crem_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 204, 80),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_OPAQUE, 655),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
