#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"
#include "group0.h"

#include "bubble/geo.inc.c"
#include "walk_smoke/geo.inc.c"
#include "burn_smoke/geo.inc.c"
#include "stomp_smoke/geo.inc.c"
#include "water_wave/geo.inc.c"
#include "sparkle/geo.inc.c"
#include "water_splash/geo.inc.c"
#include "sparkle_animation/geo.inc.c"
#include "mario/geo.inc.c"

#include "cheese_follow/geo.inc.c"
#include "mario_winter/geo.inc.c"
#include "mario_riders/geo.inc.c"
#include "mario_spring/geo.inc.c"
#include "mario_unicorn/geo.inc.c"
#include "mario_yukata/geo.inc.c"
#include "mario_vanilla/geo.inc.c"
#include "mario_bean/geo.inc.c"
#include "mario_mario/geo.inc.c"
#include "mario_luffy/geo.inc.c"
#include "mario_ichiban/geo.inc.c"
#include "mario_goku/geo.inc.c"
#include "mario_cinnia/geo.inc.c"
#include "mario_chef/geo.inc.c"
#include "mario_val/geo.inc.c"
#include "mario_roger/geo.inc.c"
#include "mario_katalina/geo.inc.c"
#include "mario_kitten/geo.inc.c"
#include "mario_layla/geo.inc.c"
#include "mario_creamocchia/geo.inc.c"
#include "wisp1/geo.inc.c"
#include "wisp2/geo.inc.c"
#include "mario_klonoa/geo.inc.c"