#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

// Note: This bin does not use bin IDs, unlike the other segmented bins.
#include "mario/model.inc.c"

#include "bubble/model.inc.c"

#include "walk_smoke/model.inc.c"

#include "burn_smoke/model.inc.c"

#include "stomp_smoke/model.inc.c"

#include "water_wave/model.inc.c"

#include "sparkle/model.inc.c"

#include "water_splash/model.inc.c"

#include "white_particle_small/model.inc.c"

#include "sparkle_animation/model.inc.c"

#include "cheese_follow/model.inc.c"
#include "cheese_follow/anims/data.inc.c"
#include "cheese_follow/anims/table.inc.c"
#include "mario_winter/model.inc.c"
#include "mario_riders/model.inc.c"
#include "mario_spring/model.inc.c"
#include "mario_unicorn/model.inc.c"
#include "mario_yukata/model.inc.c"
#include "mario_vanilla/model.inc.c"
#include "mario_bean/model.inc.c"
#include "mario_mario/model.inc.c"
#include "mario_luffy/model.inc.c"
#include "mario_ichiban/model.inc.c"
#include "mario_goku/model.inc.c"
#include "mario_cinnia/model.inc.c"
#include "mario_chef/model.inc.c"
#include "mario_val/model.inc.c"
#include "mario_roger/model.inc.c"
#include "mario_katalina/model.inc.c"
#include "mario_kitten/model.inc.c"
#include "mario_layla/model.inc.c"
#include "mario_creamocchia/model.inc.c"
#include "wisp1/model.inc.c"
#include "wisp1/anims/data.inc.c"
#include "wisp1/anims/table.inc.c"
#include "wisp2/model.inc.c"
#include "wisp2/anims/data.inc.c"
#include "wisp2/anims/table.inc.c"
#include "mario/collision.inc.c"
#include "mario_klonoa/model.inc.c"
#include "cheese_follow_spring/model.inc.c"
#include "cheese_follow_chocola/model.inc.c"
#include "cheese_follow_unicorn/model.inc.c"
#include "cheese_follow_yukata/model.inc.c"
#include "cheese_follow_bean/model.inc.c"
#include "cheese_follow_mario/model.inc.c"
#include "cheese_follow_luffy/model.inc.c"
#include "cheese_follow_klonoa/model.inc.c"
#include "cheese_follow_chef/model.inc.c"
#include "cheese_follow_val/model.inc.c"
#include "cheese_follow_ichiban/model.inc.c"
#include "cheese_follow_goku/model.inc.c"
#include "cheese_follow_cinnia/model.inc.c"
#include "cheese_follow_roger/model.inc.c"
#include "cheese_follow_creamocchia/model.inc.c"
#include "cheese_follow_layla/model.inc.c"
#include "cheese_follow_kitten/model.inc.c"
#include "cheese_follow_katalina/model.inc.c"
#include "mario_halloween/model.inc.c"
#include "cheese_follow_halloween/model.inc.c"
#include "cheese_follow_riders/model.inc.c"
#include "cheese_follow_winter/model.inc.c"
#include "mario_swimsuit/model.inc.c"
#include "cheese_follow_swimsuit/model.inc.c"
#include "mario_travis/model.inc.c"
#include "cheese_follow_travis/model.inc.c"
#include "mario_bait/model.inc.c"
#include "cheese_follow_bait/model.inc.c"
#include "mario_anya/model.inc.c"
#include "mario_wiz/model.inc.c"
#include "cheese_follow_wiz/model.inc.c"
#include "cheese_follow_anya/model.inc.c"
#include "mario_caroline/model.inc.c"
#include "mario_jack/model.inc.c"
#include "cheese_follow_jack/model.inc.c"
#include "mario_austin/model.inc.c"
#include "cheese_follow_austin/model.inc.c"
#include "mario_fly/model.inc.c"
#include "mario_anya_fly/model.inc.c"
#include "mario_austin_fly/model.inc.c"
#include "mario_caroline_fly/model.inc.c"
#include "mario_chef_fly/model.inc.c"
#include "mario_goku_fly/model.inc.c"
#include "mario_halloween_fly/model.inc.c"
#include "mario_ichiban_fly/model.inc.c"
#include "mario_jack_fly/model.inc.c"
#include "mario_yukata_fly/model.inc.c"
#include "mario_riders_fly/model.inc.c"
#include "mario_roger_fly/model.inc.c"
#include "mario_bean_fly/model.inc.c"
#include "mario_spring_fly/model.inc.c"
#include "mario_swimsuit_fly/model.inc.c"
#include "mario_travis_fly/model.inc.c"
#include "mario_unicorn_fly/model.inc.c"
#include "mario_vanilla_fly/model.inc.c"
#include "mario_winter_fly/model.inc.c"
#include "mario_wiz_fly/model.inc.c"
#include "mario_macer/model.inc.c"
#include "cheese_follow_macer/model.inc.c"
#include "mario_macer_fly/model.inc.c"
#include "mario_dudley/model.inc.c"
#include "cheese_follow_dudley/model.inc.c"
#include "mario_dudley_fly/model.inc.c"
#include "mario_pan/model.inc.c"
#include "mario_pan_fly/model.inc.c"
#include "cheese_follow_pan/model.inc.c"
#include "mario_pocky/model.inc.c"
#include "mario_pocky_fly/model.inc.c"
#include "cheese_follow_pocky/model.inc.c"
#include "mario_lan/model.inc.c"
#include "mario_lan_fly/model.inc.c"
#include "cheese_follow_lan/model.inc.c"
#include "mario_dani/model.inc.c"
#include "cheese_follow_dani/model.inc.c"
#include "mario_dani_fly/model.inc.c"
#include "mario_amy/model.inc.c"
#include "mario_amy_fly/model.inc.c"
#include "cheese_follow_amy/model.inc.c"