#include "anim_amyIdle_30.inc.c"
#include "anim_amyScared_90.inc.c"
#include "anim_AmyGhost_30.inc.c"
#include "anim_amySweaty_45.inc.c"
#include "anim_amyConfused_45.inc.c"
#include "anim_amySad_30.inc.c"
#include "anim_amyTerrified_30.inc.c"
