#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_presets.h"
#include "special_presets.h"
#include "textures.h"

#include "make_const_nonconst.h"
#include "levels/wmotr/texture.inc.c"
#include "levels/wmotr/areas/1/model.inc.c"
#include "levels/wmotr/areas/1/collision.inc.c"
#include "levels/wmotr/areas/1/macro.inc.c"

#include "levels/wmotr/leveldata.inc.c"

#include "levels/wmotr/golftree/model.inc.c"
#include "levels/wmotr/starflag/model.inc.c"
#include "levels/wmotr/starflag/anims/data.inc.c"
#include "levels/wmotr/starflag/anims/table.inc.c"
#include "levels/wmotr/johnny/anims/data.inc.c"
#include "levels/wmotr/johnny/anims/table.inc.c"
#include "levels/wmotr/johnny/model.inc.c"
#include "levels/wmotr/vector/model.inc.c"
#include "levels/wmotr/vector/anims/data.inc.c"
#include "levels/wmotr/vector/anims/table.inc.c"