extern const GeoLayout boo_castle_001_switch_opt1[];
extern const GeoLayout boo_castle_geo[];
extern Lights1 boo_castle_eyes_f3d_lights;
extern Lights1 boo_castle_eyes2_f3d_lights;
extern Lights1 boo_castle_teeth2_f3d_lights;
extern u8 boo_castle_eyes_ci8[];
extern u8 boo_castle_eyes_ci8_pal_rgba16[];
extern u8 boo_castle_eyes2_i8[];
extern u8 boo_castle_teeth2_i8[];
extern Vtx boo_castle_000_displaylist_mesh_layer_1_vtx_0[70];
extern Gfx boo_castle_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx boo_castle_000_displaylist_mesh_layer_1_vtx_1[6];
extern Gfx boo_castle_000_displaylist_mesh_layer_1_tri_1[];
extern Vtx boo_castle_000_displaylist_mesh_layer_1_vtx_2[15];
extern Gfx boo_castle_000_displaylist_mesh_layer_1_tri_2[];
extern Gfx mat_boo_castle_eyes_f3d[];
extern Gfx mat_revert_boo_castle_eyes_f3d[];
extern Gfx mat_boo_castle_eyes2_f3d[];
extern Gfx mat_boo_castle_teeth2_f3d[];
extern Gfx boo_castle_000_displaylist_mesh_layer_1[];
extern Gfx boo_castle_material_revert_render_settings[];
