#include "src/game/envfx_snow.h"

const GeoLayout marine_Marine_halfopen[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 143, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, marine_Head_Switch_000_Head_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, marine_Head_Switch_000_Head_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout marine_Marine_closed[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 143, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, marine_Head_Switch_001_Head_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, marine_Head_Switch_001_Head_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout marine_Marine_happy[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 143, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, marine_Head_Switch_002_Head_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, marine_Head_Switch_002_Head_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout marine_Marine_sorry[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 143, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, marine_Head_Switch_003_Head_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, marine_Head_Switch_003_Head_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout marine_Marine_tired[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 143, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, marine_Head_Switch_004_Head_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, marine_Head_Switch_004_Head_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout marine_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 204, 80),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_OPAQUE, 5898),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 587, 0, 0, -180, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, marine_Root_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, marine_Chest_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 132, 0, marine_Chest_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_SWITCH_CASE(0, geo_switch_marine_face),
							GEO_OPEN_NODE(),
								GEO_NODE_START(),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 143, 0, marine_Head_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, marine_Head_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_BRANCH(1, marine_Marine_halfopen),
								GEO_BRANCH(1, marine_Marine_closed),
								GEO_BRANCH(1, marine_Marine_happy),
								GEO_BRANCH(1, marine_Marine_sorry),
								GEO_BRANCH(1, marine_Marine_tired),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -88, 111, 0, marine_lArm_001_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, marine_lArm_002_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, -162, 0, 0, marine_lArm_002_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, -188, 0, 0, marine_lArm_003_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 88, 111, 0, marine_rArm_001_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, marine_rArm_002_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 151, 0, 0, marine_rArm_002_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 184, 0, 0, marine_rArm_003_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 18, 101, marine_Tail_001_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, marine_Tail_002_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 256, marine_Tail_002_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, marine_Tail_003_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 2, 297, marine_Tail_003_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, marine_lLeg_001_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -52, 0, 0, marine_lLeg_001_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, marine_lLeg_002_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -13, -167, 0, marine_lLeg_002_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, -1, -212, 0, marine_lLeg_003_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, marine_rLeg_001_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 54, 0, 0, marine_rLeg_001_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, marine_rLeg_002_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 3, -167, 0, marine_rLeg_002_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 15, -211, 0, marine_rLeg_003_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, marine_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, marine_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
