#include "src/game/envfx_snow.h"

const GeoLayout tammie_Head_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_ALPHA, 0, 172, -51, tammie_Head_mesh_layer_4_mat_override_face_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, tammie_Head_mesh_layer_1_mat_override_face_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout tammie_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 204, 80),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_OPAQUE, 10486),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_ALPHA, 0, 118, 28, tammie_Root_mesh_layer_4),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, tammie_Root_mesh_layer_1),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, tammie_Chest_skinned_mesh_layer_1),
					GEO_DISPLAY_LIST(LAYER_ALPHA, tammie_Chest_skinned_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 103, 6, tammie_Chest_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, tammie_Chest_mesh_layer_4),
						GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_ALPHA, 0, 172, -51, tammie_Head_mesh_layer_4),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, tammie_Head_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, tammie_Head_Switch_opt1),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, 42, 131, -50, tammie_lArm_001_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, tammie_lArm_002_skinned_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_ALPHA, 164, 0, 0, tammie_lArm_002_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_ALPHA, 210, 0, 0, tammie_lArm_003_mesh_layer_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, -35, 131, -50, tammie_rArm_001_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, tammie_rArm_002_skinned_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_ALPHA, -167, 0, 0, tammie_rArm_002_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_ALPHA, -210, 0, 0, tammie_rArm_003_mesh_layer_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 56, -68, -28, tammie_lLeg_001_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, tammie_lLeg_001_mesh_layer_1),
						GEO_DISPLAY_LIST(LAYER_ALPHA, tammie_lLeg_002_skinned_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, -25, -229, 17, tammie_lLeg_002_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, tammie_lLeg_003_skinned_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_ALPHA, -11, -234, -44, tammie_lLeg_003_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, -54, -68, -28, tammie_rLeg_001_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, tammie_rLeg_001_mesh_layer_1),
						GEO_DISPLAY_LIST(LAYER_ALPHA, tammie_rLeg_002_skinned_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, 20, -225, 17, tammie_rLeg_002_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, tammie_rLeg_003_skinned_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_ALPHA, 16, -238, -44, tammie_rLeg_003_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, tammie_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, tammie_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
