extern const GeoLayout peach_jack_001_switch_opt1_000_switch_opt1[];
extern const GeoLayout peach_jack_001_switch_opt1_000_switch_opt2[];
extern const GeoLayout peach_jack_001_switch_opt1_000_switch_opt3[];
extern const GeoLayout peach_jack_001_switch_opt1_000_switch_opt4[];
extern const GeoLayout peach_jack_001_switch_opt1_000_switch_opt5[];
extern const GeoLayout peach_jack_001_switch_opt1_000_switch_opt6[];
extern const GeoLayout peach_jack_001_switch_opt1_000_switch_opt7[];
extern const GeoLayout peach_jack_001_switch_opt1[];
extern const GeoLayout peach_jack_001_switch_opt0_000_switch_opt1[];
extern const GeoLayout peach_jack_001_switch_opt0_000_switch_opt2[];
extern const GeoLayout peach_jack_001_switch_opt0_000_switch_opt3[];
extern const GeoLayout peach_jack_001_switch_opt0_000_switch_opt4[];
extern const GeoLayout peach_jack_001_switch_opt0_000_switch_opt5[];
extern const GeoLayout peach_jack_001_switch_opt0_000_switch_opt6[];
extern const GeoLayout peach_jack_001_switch_opt0_000_switch_opt7[];
extern const GeoLayout peach_jack_geo[];
extern Lights1 peach_jack_dress_f3d_v4_lights;
extern Lights1 peach_jack_j_colors_001_lights;
extern Lights1 peach_jack_m_colors_f3d_f3d_v4_lights;
extern Lights1 peach_jack_jewel_f3d_v4_lights;
extern Lights1 peach_jack_crown_base_f3d_v4_lights;
extern Lights1 peach_jack_crown_jewel_f3d_v4_lights;
extern Lights1 peach_jack_jack_eyes_lights;
extern Lights1 peach_jack_jack_face_lights;
extern Lights1 peach_jack_jack_furshade_lights;
extern Lights1 peach_jack_jack_mouth_lights;
extern Lights1 peach_jack_j_colors_lights;
extern Lights1 peach_jack_jack_eyes2_lights;
extern Lights1 peach_jack_jack_eyes3_lights;
extern Lights1 peach_jack_jack_eyes4_lights;
extern u8 peach_jack_j_dress_ci4[];
extern u8 peach_jack_j_dress_ci4_pal_rgba16[];
extern u8 peach_jack_j_colors_ci8[];
extern u8 peach_jack_j_colors_ci8_pal_rgba16[];
extern u8 peach_jack_j_colors_ci8_copy[];
extern u8 peach_jack_j_colors_ci8_pal_rgba16_copy[];
extern u8 peach_jack_v_chest_ci8[];
extern u8 peach_jack_v_chest_ci8_pal_rgba16[];
extern u8 peach_jack_v_crown_ci8[];
extern u8 peach_jack_v_crown_ci8_pal_rgba16[];
extern u8 peach_jack_jack_eyes1_ci8[];
extern u8 peach_jack_jack_eyes1_ci8_pal_rgba16[];
extern u8 peach_jack_jack_muzzle_ci8[];
extern u8 peach_jack_jack_muzzle_ci8_pal_rgba16[];
extern u8 peach_jack_j_furshade_ci8[];
extern u8 peach_jack_j_furshade_ci8_pal_rgba16[];
extern u8 peach_jack_jack_mouth_ci4[];
extern u8 peach_jack_jack_mouth_ci4_pal_rgba16[];
extern u8 peach_jack_j_colors_ci8_copy_copy[];
extern u8 peach_jack_j_colors_ci8_pal_rgba16_copy_copy[];
extern u8 peach_jack_jack_eyes2_ci8[];
extern u8 peach_jack_jack_eyes2_ci8_pal_rgba16[];
extern u8 peach_jack_jack_eyes3_ci8[];
extern u8 peach_jack_jack_eyes3_ci8_pal_rgba16[];
extern u8 peach_jack_jack_eyes4_ci8[];
extern u8 peach_jack_jack_eyes4_ci8_pal_rgba16[];
extern Vtx peach_jack_000_offset_001_mesh_layer_1_vtx_0[53];
extern Gfx peach_jack_000_offset_001_mesh_layer_1_tri_0[];
extern Vtx peach_jack_000_offset_001_mesh_layer_4_vtx_0[16];
extern Gfx peach_jack_000_offset_001_mesh_layer_4_tri_0[];
extern Vtx peach_jack_000_offset_002_mesh_layer_1_vtx_0[60];
extern Gfx peach_jack_000_offset_002_mesh_layer_1_tri_0[];
extern Vtx peach_jack_000_offset_002_mesh_layer_1_vtx_1[90];
extern Gfx peach_jack_000_offset_002_mesh_layer_1_tri_1[];
extern Vtx peach_jack_000_offset_002_mesh_layer_1_vtx_2[9];
extern Gfx peach_jack_000_offset_002_mesh_layer_1_tri_2[];
extern Vtx peach_jack_000_displaylist_mesh_layer_1_vtx_0[41];
extern Gfx peach_jack_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx peach_jack_000_displaylist_mesh_layer_1_vtx_1[16];
extern Gfx peach_jack_000_displaylist_mesh_layer_1_tri_1[];
extern Vtx peach_jack_000_displaylist_mesh_layer_1_vtx_2[36];
extern Gfx peach_jack_000_displaylist_mesh_layer_1_tri_2[];
extern Vtx peach_jack_000_displaylist_mesh_layer_1_vtx_3[115];
extern Gfx peach_jack_000_displaylist_mesh_layer_1_tri_3[];
extern Vtx peach_jack_000_displaylist_mesh_layer_1_vtx_4[132];
extern Gfx peach_jack_000_displaylist_mesh_layer_1_tri_4[];
extern Vtx peach_jack_000_displaylist_mesh_layer_1_vtx_5[7];
extern Gfx peach_jack_000_displaylist_mesh_layer_1_tri_5[];
extern Vtx peach_jack_000_displaylist_mesh_layer_4_vtx_0[21];
extern Gfx peach_jack_000_displaylist_mesh_layer_4_tri_0[];
extern Vtx peach_jack_000_offset_005_mesh_layer_1_vtx_0[75];
extern Gfx peach_jack_000_offset_005_mesh_layer_1_tri_0[];
extern Vtx peach_jack_000_offset_005_mesh_layer_1_vtx_1[16];
extern Gfx peach_jack_000_offset_005_mesh_layer_1_tri_1[];
extern Vtx peach_jack_000_offset_006_mesh_layer_1_vtx_0[72];
extern Gfx peach_jack_000_offset_006_mesh_layer_1_tri_0[];
extern Vtx peach_jack_000_offset_007_mesh_layer_1_vtx_0[35];
extern Gfx peach_jack_000_offset_007_mesh_layer_1_tri_0[];
extern Vtx peach_jack_002_offset_002_mesh_layer_1_vtx_0[31];
extern Gfx peach_jack_002_offset_002_mesh_layer_1_tri_0[];
extern Vtx peach_jack_000_offset_008_mesh_layer_1_vtx_0[74];
extern Gfx peach_jack_000_offset_008_mesh_layer_1_tri_0[];
extern Vtx peach_jack_000_offset_008_mesh_layer_1_vtx_1[16];
extern Gfx peach_jack_000_offset_008_mesh_layer_1_tri_1[];
extern Vtx peach_jack_000_offset_009_mesh_layer_1_vtx_0[73];
extern Gfx peach_jack_000_offset_009_mesh_layer_1_tri_0[];
extern Vtx peach_jack_000_offset_010_mesh_layer_1_vtx_0[41];
extern Gfx peach_jack_000_offset_010_mesh_layer_1_tri_0[];
extern Vtx peach_jack_002_offset_003_mesh_layer_1_vtx_0[31];
extern Gfx peach_jack_002_offset_003_mesh_layer_1_tri_0[];
extern Vtx peach_jack_000_offset_011_mesh_layer_1_vtx_0[16];
extern Gfx peach_jack_000_offset_011_mesh_layer_1_tri_0[];
extern Vtx peach_jack_000_offset_011_mesh_layer_1_vtx_1[100];
extern Gfx peach_jack_000_offset_011_mesh_layer_1_tri_1[];
extern Gfx mat_peach_jack_dress_f3d_v4[];
extern Gfx mat_revert_peach_jack_dress_f3d_v4[];
extern Gfx mat_peach_jack_j_colors_001[];
extern Gfx mat_revert_peach_jack_j_colors_001[];
extern Gfx mat_peach_jack_m_colors_f3d_f3d_v4[];
extern Gfx mat_revert_peach_jack_m_colors_f3d_f3d_v4[];
extern Gfx mat_peach_jack_jewel_f3d_v4[];
extern Gfx mat_revert_peach_jack_jewel_f3d_v4[];
extern Gfx mat_peach_jack_crown_base_f3d_v4[];
extern Gfx mat_peach_jack_crown_jewel_f3d_v4[];
extern Gfx mat_revert_peach_jack_crown_jewel_f3d_v4[];
extern Gfx mat_peach_jack_jack_eyes[];
extern Gfx mat_revert_peach_jack_jack_eyes[];
extern Gfx mat_peach_jack_jack_face[];
extern Gfx mat_revert_peach_jack_jack_face[];
extern Gfx mat_peach_jack_jack_furshade[];
extern Gfx mat_revert_peach_jack_jack_furshade[];
extern Gfx mat_peach_jack_jack_mouth[];
extern Gfx mat_revert_peach_jack_jack_mouth[];
extern Gfx mat_peach_jack_j_colors[];
extern Gfx mat_revert_peach_jack_j_colors[];
extern Gfx mat_peach_jack_jack_eyes2[];
extern Gfx mat_revert_peach_jack_jack_eyes2[];
extern Gfx mat_peach_jack_jack_eyes3[];
extern Gfx mat_revert_peach_jack_jack_eyes3[];
extern Gfx mat_peach_jack_jack_eyes4[];
extern Gfx mat_revert_peach_jack_jack_eyes4[];
extern Gfx peach_jack_000_offset_001_mesh_layer_1[];
extern Gfx peach_jack_000_offset_001_mesh_layer_4[];
extern Gfx peach_jack_000_offset_002_mesh_layer_1[];
extern Gfx peach_jack_000_displaylist_mesh_layer_1[];
extern Gfx peach_jack_000_displaylist_mesh_layer_1_mat_override_jack_eyes_0[];
extern Gfx peach_jack_000_displaylist_mesh_layer_1_mat_override_jack_eyes2_1[];
extern Gfx peach_jack_000_displaylist_mesh_layer_1_mat_override_jack_eyes3_2[];
extern Gfx peach_jack_000_displaylist_mesh_layer_1_mat_override_jack_eyes4_3[];
extern Gfx peach_jack_000_displaylist_mesh_layer_4[];
extern Gfx peach_jack_000_displaylist_mesh_layer_4_mat_override_jack_eyes_0[];
extern Gfx peach_jack_000_displaylist_mesh_layer_4_mat_override_jack_eyes2_1[];
extern Gfx peach_jack_000_displaylist_mesh_layer_4_mat_override_jack_eyes3_2[];
extern Gfx peach_jack_000_displaylist_mesh_layer_4_mat_override_jack_eyes4_3[];
extern Gfx peach_jack_000_offset_005_mesh_layer_1[];
extern Gfx peach_jack_000_offset_006_mesh_layer_1[];
extern Gfx peach_jack_000_offset_007_mesh_layer_1[];
extern Gfx peach_jack_002_offset_002_mesh_layer_1[];
extern Gfx peach_jack_000_offset_008_mesh_layer_1[];
extern Gfx peach_jack_000_offset_009_mesh_layer_1[];
extern Gfx peach_jack_000_offset_010_mesh_layer_1[];
extern Gfx peach_jack_002_offset_003_mesh_layer_1[];
extern Gfx peach_jack_000_offset_011_mesh_layer_1[];
extern Gfx peach_jack_material_revert_render_settings[];
