#include "src/game/envfx_snow.h"

const GeoLayout blaze_Blaze_halfblink[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 154, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, blaze_Head_Switch_001_Head_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, blaze_Head_Switch_001_Head_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 477, -290, blaze_Head_Switch_001_Ponytail_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout blaze_Blaze_closed[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 154, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, blaze_Head_Switch_002_Head_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, blaze_Head_Switch_002_Head_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 477, -290, blaze_Head_Switch_002_Ponytail_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout blaze_Blaze_sigh[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 154, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, blaze_Head_Switch_003_Head_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, blaze_Head_Switch_003_Head_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 477, -290, blaze_Head_Switch_003_Ponytail_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout blaze_Blaze_happy[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 154, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, blaze_Head_Switch_004_Head_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, blaze_Head_Switch_004_Head_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 477, -290, blaze_Head_Switch_004_Ponytail_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout blaze_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 204, 80),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_OPAQUE, 8520),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, blaze_Root_mesh_layer_4),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 121, 0, blaze_Chest_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, blaze_Chest_mesh_layer_1),
						GEO_SWITCH_CASE(0, geo_switch_blaze_face),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_ALPHA, 0, 154, 0, blaze_Head_mesh_layer_4),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, blaze_Head_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 477, -290, blaze_Ponytail_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, blaze_Blaze_halfblink),
							GEO_BRANCH(1, blaze_Blaze_closed),
							GEO_BRANCH(1, blaze_Blaze_sigh),
							GEO_BRANCH(1, blaze_Blaze_happy),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, 85, 113, 0, blaze_lArm_001_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, blaze_lArm_002_skinned_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_ALPHA, 137, 0, 0, blaze_lArm_002_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, blaze_lArm_002_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_ALPHA, 205, 0, 0, blaze_lArm_003_mesh_layer_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, -88, 113, 0, blaze_rArm_001_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, blaze_rArm_002_skinned_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_ALPHA, -133, 0, 0, blaze_rArm_002_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, blaze_rArm_002_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_ALPHA, -207, 0, 0, blaze_rArm_003_mesh_layer_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 35, -68, blaze_Tail_001_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, blaze_Tail_003_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -9, -153, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -6, -170, blaze_Tail_003_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, blaze_Tail_004_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -13, -221, blaze_Tail_004_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_ALPHA, blaze_Tail_004_mesh_layer_4),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 54, 53, 0, blaze_lLeg_001_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, blaze_lLeg_002_skinned_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, 0, -182, 0, blaze_lLeg_002_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 3, -254, 0, blaze_lLeg_003_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, -52, 53, 0, blaze_rLeg_001_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, blaze_rLeg_002_skinned_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, -4, -178, 0, blaze_rLeg_002_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -1, -258, 0, blaze_rLeg_003_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, blaze_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, blaze_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
