#include "src/game/envfx_snow.h"

const GeoLayout vcutm_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, vcutm_dl_building_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, vcutm_dl_building_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, vcutm_dl_building_render_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, vcutm_dl_building_render_mesh_layer_1),
		GEO_ROTATION_NODE_WITH_DL(LAYER_ALPHA, 90, 0, 180, vcutm_dl_Chateau_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, vcutm_dl_Chateau_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, vcutm_dl_DunkTank_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, vcutm_dl_DunkTank_mesh_layer_4),
		GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 0, -9, 0, vcutm_dl_FerrisWheel_RenderOnly_mesh_layer_1),
		GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 0, -9, 0, vcutm_dl_FerrisWheel_Solid_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, vcutm_dl_FerrisWheel_Solid_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, vcutm_dl_ice_fountain_chao_statue_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, vcutm_dl_ice_fountain_chao_statue_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, vcutm_dl_MainLevel_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, vcutm_dl_MainLevel_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, vcutm_dl_MainLevel_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, vcutm_dl_MainLevel_Render_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, vcutm_dl_MainLevel_Render_mesh),
		GEO_DISPLAY_LIST(LAYER_ALPHA, vcutm_dl_MainLevel_Render_mesh_layer_4),
		GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 90, 0, 180, vcutm_dl_Pirate_Ship_Main_mesh_layer_1),
		GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 90, 0, 180, vcutm_dl_Pirate_Ship_Render_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, vcutm_dl_Pirate_Ship_Render_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_ALPHA, -2422, 422, 5481, 0, -46, 0, vcutm_dl_trees_2D_mesh_layer_4),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -6538, 212, 6570, 90, 0, -17, vcutm_dl_trees_3D_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout vcutm_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_SNOW_MOUNTAINS, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, vcutm_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_SNOW_NORMAL, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, vcutm_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, vcutm_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, vcutm_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
