#include "src/game/envfx_snow.h"

const GeoLayout silver_000_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 54, 0, silver_Head_mesh_layer_1_mat_override_eyeblink_half_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout silver_000_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 54, 0, silver_Head_mesh_layer_1_mat_override_eyeblink_closed_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout silver_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 178, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_OPAQUE, 13107),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -18, 0, silver_Root_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, silver_Chest_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 100, 0, silver_Chest_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, silver_Chest_mesh_layer_4),
						GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 54, 0, silver_Head_mesh_layer_1),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, silver_000_switch_opt1),
							GEO_BRANCH(1, silver_000_switch_opt2),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 59, 30, 0, silver_Arm_L_01_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, silver_Arm_L_02_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 95, 0, 0, silver_Arm_L_02_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 138, 0, 0, silver_Hand_L_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -53, 30, 0, silver_Arm_R_01_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, silver_Arm_R_02_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -100, 0, 0, silver_Arm_R_02_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, -119, 0, 0, silver_Hand_R_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 37, -3, 0, silver_Leg_L_01_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, silver_Leg_L_02_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -125, 0, silver_Leg_L_02_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -152, 0, silver_Foot_L_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -37, -3, 0, silver_Leg_R_01_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, silver_Leg_R_02_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -126, 0, silver_Leg_R_02_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -150, 0, silver_Foot_R_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, silver_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, silver_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
