#include "src/game/envfx_snow.h"

const GeoLayout sorbet_Head_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_ALPHA, 0, 70, 0, sorbet_Head_mesh_layer_4_mat_override_eyes_f3d_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, sorbet_Head_mesh_layer_1_mat_override_eyes_f3d_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sorbet_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 204, 80),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_OPAQUE, 13107),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_ALPHA, 0, 26, 0, sorbet_Root_mesh_layer_4),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, sorbet_Root_mesh_layer_1),
					GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 70, 0, sorbet_Head_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, sorbet_Head_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_BRANCH(1, sorbet_Head_Switch_opt1),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 77, 58, 0, sorbet_lArm_001_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, 54, -51, 49, sorbet_lLeg_001_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, sorbet_lLeg_001_mesh_layer_1),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, -77, 62, 0, sorbet_rArm_001_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, -52, -51, 49, sorbet_rLeg_001_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, sorbet_rLeg_001_mesh_layer_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sorbet_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sorbet_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
