#include "levels/cotmc/area_1/collision.inc.c"
#include "levels/cotmc/area_1/macro.inc.c"
#include "levels/cotmc/area_1/spline.inc.c"
#include "levels/cotmc/area_2/collision.inc.c"
#include "levels/cotmc/area_2/macro.inc.c"
#include "levels/cotmc/area_2/spline.inc.c"
#include "levels/cotmc/model.inc.c"
