#include "src/game/envfx_snow.h"

const GeoLayout peach_creamocchia_ArmatureObj_hb2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_creamocchia_001_switch_000_displaylist_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, peach_creamocchia_001_switch_000_displaylist_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_creamocchia_ArmatureObj_c2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_creamocchia_003_switch_000_displaylist_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, peach_creamocchia_003_switch_000_displaylist_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_creamocchia_ArmatureObj_s[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_creamocchia_004_switch_000_displaylist_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, peach_creamocchia_004_switch_000_displaylist_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_creamocchia_ArmatureObj_hb1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_creamocchia_000_switch_000_displaylist_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, peach_creamocchia_000_switch_000_displaylist_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_creamocchia_ArmatureObj_c1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_creamocchia_002_switch_000_displaylist_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, peach_creamocchia_002_switch_000_displaylist_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_creamocchia_001_switch_opt1_jump_peach_creamocchia_ArmatureObj_hb2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_creamocchia_001_switch_000_displaylist_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_creamocchia_001_switch_000_displaylist_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_creamocchia_001_switch_opt1_jump_peach_creamocchia_ArmatureObj_c2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_creamocchia_003_switch_000_displaylist_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_creamocchia_003_switch_000_displaylist_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_creamocchia_001_switch_opt1_jump_peach_creamocchia_ArmatureObj_s[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_creamocchia_004_switch_000_displaylist_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_creamocchia_004_switch_000_displaylist_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_creamocchia_001_switch_opt1_jump_peach_creamocchia_ArmatureObj_hb1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_creamocchia_000_switch_000_displaylist_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_creamocchia_000_switch_000_displaylist_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_creamocchia_001_switch_opt1_jump_peach_creamocchia_ArmatureObj_c1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_creamocchia_002_switch_000_displaylist_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_creamocchia_002_switch_000_displaylist_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_creamocchia_001_switch_opt1_000_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_creamocchia_000_displaylist_mesh_layer_1_mat_override_face_open_0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_creamocchia_000_displaylist_mesh_layer_4_mat_override_face_open_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_creamocchia_001_switch_opt1_000_switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_creamocchia_000_displaylist_mesh_layer_1_mat_override_face_open_0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_creamocchia_000_displaylist_mesh_layer_4_mat_override_face_open_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_creamocchia_001_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_creamocchia_000_offset_001_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, peach_creamocchia_000_offset_002_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_SWITCH_CASE(8, geo_switch_peach_eyes),
							GEO_OPEN_NODE(),
								GEO_NODE_START(),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_creamocchia_000_displaylist_mesh_layer_1),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_creamocchia_000_displaylist_mesh_layer_4),
								GEO_CLOSE_NODE(),
								GEO_BRANCH(1, peach_creamocchia_001_switch_opt1_000_switch_opt1),
								GEO_BRANCH(1, peach_creamocchia_001_switch_opt1_jump_peach_creamocchia_ArmatureObj_hb2),
								GEO_BRANCH(1, peach_creamocchia_001_switch_opt1_jump_peach_creamocchia_ArmatureObj_c2),
								GEO_BRANCH(1, peach_creamocchia_001_switch_opt1_jump_peach_creamocchia_ArmatureObj_s),
								GEO_BRANCH(1, peach_creamocchia_001_switch_opt1_000_switch_opt5),
								GEO_BRANCH(1, peach_creamocchia_001_switch_opt1_jump_peach_creamocchia_ArmatureObj_hb1),
								GEO_BRANCH(1, peach_creamocchia_001_switch_opt1_jump_peach_creamocchia_ArmatureObj_c1),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 38, -78, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 0, 0, NULL),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 0, 0, NULL),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, 84, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_creamocchia_000_offset_005_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 104, 0, 0, peach_creamocchia_000_offset_006_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, peach_creamocchia_000_offset_007_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_creamocchia_002_offset_002_mesh_layer_1),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, -84, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_creamocchia_000_offset_008_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 104, 0, 0, peach_creamocchia_000_offset_009_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, peach_creamocchia_000_offset_010_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_creamocchia_002_offset_003_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, NULL),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -23, -1, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_creamocchia_000_offset_011_mesh_layer_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_creamocchia_001_switch_opt0_000_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_creamocchia_000_displaylist_mesh_layer_1_mat_override_face_open_0),
		GEO_DISPLAY_LIST(LAYER_ALPHA, peach_creamocchia_000_displaylist_mesh_layer_4_mat_override_face_open_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_creamocchia_001_switch_opt0_000_switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_creamocchia_000_displaylist_mesh_layer_1_mat_override_face_open_0),
		GEO_DISPLAY_LIST(LAYER_ALPHA, peach_creamocchia_000_displaylist_mesh_layer_4_mat_override_face_open_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout peach_creamocchia_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(10, geo_update_layer_transparency),
				GEO_SWITCH_CASE(2, geo_switch_anim_state),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_creamocchia_000_offset_001_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, peach_creamocchia_000_offset_002_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(8, geo_switch_peach_eyes),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_creamocchia_000_displaylist_mesh_layer_1),
													GEO_DISPLAY_LIST(LAYER_ALPHA, peach_creamocchia_000_displaylist_mesh_layer_4),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, peach_creamocchia_001_switch_opt0_000_switch_opt1),
												GEO_BRANCH(1, peach_creamocchia_ArmatureObj_hb2),
												GEO_BRANCH(1, peach_creamocchia_ArmatureObj_c2),
												GEO_BRANCH(1, peach_creamocchia_ArmatureObj_s),
												GEO_BRANCH(1, peach_creamocchia_001_switch_opt0_000_switch_opt5),
												GEO_BRANCH(1, peach_creamocchia_ArmatureObj_hb1),
												GEO_BRANCH(1, peach_creamocchia_ArmatureObj_c1),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 38, -78, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 0, 0, NULL),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 0, 0, NULL),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, 84, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_creamocchia_000_offset_005_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 104, 0, 0, peach_creamocchia_000_offset_006_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, peach_creamocchia_000_offset_007_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_creamocchia_002_offset_002_mesh_layer_1),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, -84, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_creamocchia_000_offset_008_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 104, 0, 0, peach_creamocchia_000_offset_009_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, peach_creamocchia_000_offset_010_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_creamocchia_002_offset_003_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, NULL),
									GEO_ANIMATED_PART(LAYER_OPAQUE, -23, -1, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_creamocchia_000_offset_011_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, peach_creamocchia_001_switch_opt1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_creamocchia_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, peach_creamocchia_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_creamocchia_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
