extern const GeoLayout gremlin_nm_geo[];
extern Lights1 gremlin_nm_nightmare_lights;
extern u8 gremlin_nm_nightmare_ci8[];
extern u8 gremlin_nm_nightmare_pal_rgba16[];
extern Vtx gremlin_nm_000_offset_002_mesh_layer_4_vtx_0[4];
extern Gfx gremlin_nm_000_offset_002_mesh_layer_4_tri_0[];
extern Vtx gremlin_nm_000_offset_003_mesh_layer_4_vtx_0[4];
extern Gfx gremlin_nm_000_offset_003_mesh_layer_4_tri_0[];
extern Vtx gremlin_nm_000_offset_004_mesh_layer_4_vtx_0[4];
extern Gfx gremlin_nm_000_offset_004_mesh_layer_4_tri_0[];
extern Gfx mat_gremlin_nm_nightmare[];
extern Gfx mat_revert_gremlin_nm_nightmare[];
extern Gfx gremlin_nm_000_offset_002_mesh_layer_4[];
extern Gfx gremlin_nm_000_offset_003_mesh_layer_4[];
extern Gfx gremlin_nm_000_offset_004_mesh_layer_4[];
extern Gfx gremlin_nm_material_revert_render_settings[];
