#include "src/game/envfx_snow.h"

const GeoLayout unagi_geo[] = {
	GEO_CULLING_RADIUS(2000),
	GEO_OPEN_NODE(),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, unagi_000_offset_001_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, unagi_000_offset_001_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 245, 0, 0, unagi_000_offset_002_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, unagi_000_offset_002_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 494, 0, 0, unagi_000_offset_003_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, unagi_000_offset_003_mesh_layer_4),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 475, 0, 0, unagi_000_offset_004_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_ALPHA, unagi_000_offset_004_mesh_layer_4),
                           GEO_SWITCH_CASE(2, geo_switch_anim_state),
                           GEO_OPEN_NODE(),
                              GEO_NODE_START(),
                              GEO_NODE_START(),
                              GEO_OPEN_NODE(),
                                 GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 500, 0, 0, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_BRANCH_AND_LINK(star_geo),
										GEO_CLOSE_NODE(),
                              GEO_CLOSE_NODE(),
                           GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -254, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, unagi_000_offset_005_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, unagi_000_offset_005_mesh_layer_4),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 527, 0, 0, unagi_000_offset_006_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 226, 65, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, unagi_000_offset_008_mesh_layer_4),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, unagi_001_offset_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_ALPHA, 527, 0, 0, unagi_002_offset_002_mesh_layer_4),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 527, 0, 0, unagi_003_offset_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_ALPHA, unagi_003_offset_mesh_layer_4),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 527, 0, 0, NULL),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, unagi_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, unagi_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
