#include "src/game/envfx_snow.h"

const GeoLayout wiggler_head_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_BILLBOARD_WITH_PARAMS(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, wiggler_head_000_displaylist_mesh_layer_4),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 157, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_BILLBOARD_WITH_PARAMS(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, wiggler_head_000_displaylist_001_mesh_layer_4),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -14, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_BILLBOARD_WITH_PARAMS(LAYER_FORCE, 0, 0, 0),
								GEO_OPEN_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -14, 0, 0, NULL),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, 157, 0, 0, wiggler_head_003_offset_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, 157, 0, 0, wiggler_head_004_offset_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, 157, 0, 0, wiggler_head_005_offset_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -16, 23, 51, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, wiggler_head_000_offset_004_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 39, 0, 0, wiggler_head_000_offset_005_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 41, 0, 0, wiggler_head_000_offset_006_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -16, 23, -49, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, wiggler_head_000_offset_007_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 39, 0, 0, wiggler_head_000_offset_008_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 41, 0, 0, wiggler_head_000_offset_009_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wiggler_head_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, wiggler_head_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
