#include "src/game/envfx_snow.h"

const GeoLayout hocus_Hocus_HB[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 243, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, hocus_Switch_001_Head_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, hocus_Switch_001_Head_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout hocus_Hocus_C[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 243, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, hocus_Switch_002_Head_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, hocus_Switch_002_Head_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout hocus_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 204, 80),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_OPAQUE, 7864),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_ALPHA, 3, 470, 0, hocus_Root_mesh_layer_4),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_ALPHA, hocus_Chest_skinned_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, -3, 201, 0, hocus_Chest_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_npc_face),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_ALPHA, 0, 243, 0, hocus_Head_mesh_layer_4),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, hocus_Head_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, hocus_Hocus_HB),
							GEO_BRANCH(1, hocus_Hocus_C),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, 126, 151, 0, hocus_lArm_001_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, hocus_lArm_002_skinned_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_ALPHA, 167, 0, 0, hocus_lArm_002_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_ALPHA, 172, 0, 0, hocus_lArm_003_mesh_layer_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, -126, 151, 0, hocus_rArm_001_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, hocus_rArm_002_skinned_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_ALPHA, -166, 0, 0, hocus_rArm_002_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_ALPHA, -182, 0, 0, hocus_rArm_003_mesh_layer_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 77, 0, 0, hocus_lLeg_001_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, hocus_lLeg_002_skinned_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, 1, -181, 0, hocus_lLeg_002_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, -195, 0, hocus_lLeg_003_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, hocus_lLeg_003_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, -71, 0, 0, hocus_rLeg_001_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, hocus_rLeg_002_skinned_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, -1, -177, 0, hocus_rLeg_002_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 1, -199, 0, hocus_rLeg_003_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, hocus_rLeg_003_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, hocus_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, hocus_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
