extern const GeoLayout bowser_key_cutscene_unused_geo[];
extern Lights1 bowser_key_cutscene_sm64_material_005_lights;
extern Vtx bowser_key_cutscene_000_displaylist_mesh_layer_1_vtx_0[185];
extern Gfx bowser_key_cutscene_000_displaylist_mesh_layer_1_tri_0[];
extern Gfx mat_bowser_key_cutscene_sm64_material_005[];
extern Gfx bowser_key_cutscene_000_displaylist_mesh_layer_1[];
extern Gfx bowser_key_cutscene_material_revert_render_settings[];
