#include "src/game/envfx_snow.h"

const GeoLayout kz_nekoarc_Head_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 302, 0, kz_nekoarc_Head_mesh_layer_1_mat_override_eyes_halfopen_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kz_nekoarc_Head_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 302, 0, kz_nekoarc_Head_mesh_layer_1_mat_override_eyes_closed_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kz_nekoarc_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 204, 80),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_OPAQUE, 5898),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kz_nekoarc_Root_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_ALPHA, kz_nekoarc_Root_mesh_layer_4),
					GEO_DISPLAY_LIST(LAYER_ALPHA, kz_nekoarc_Chest_skinned_mesh_layer_4),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_nekoarc_Chest_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 173, 0, kz_nekoarc_Chest_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_nekoarc_Chest_mesh_layer_1),
						GEO_SWITCH_CASE(0, geo_switch_npc_face),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 302, 0, kz_nekoarc_Head_mesh_layer_1),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, kz_nekoarc_Head_Switch_opt1),
							GEO_BRANCH(1, kz_nekoarc_Head_Switch_opt2),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, 177, 183, 0, kz_nekoarc_lArm_001_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, kz_nekoarc_lArm_002_skinned_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_ALPHA, 163, 0, 0, kz_nekoarc_lArm_002_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_nekoarc_lArm_002_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 261, 0, 0, kz_nekoarc_lArm_003_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, -153, 183, 0, kz_nekoarc_rArm_001_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, kz_nekoarc_rArm_002_skinned_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_ALPHA, -133, 0, 0, kz_nekoarc_rArm_002_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_nekoarc_rArm_002_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, -309, 0, 0, kz_nekoarc_rArm_003_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 34, -176, kz_nekoarc_Tail_001_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_nekoarc_Tail_002_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, -170, kz_nekoarc_Tail_002_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_nekoarc_Tail_003_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, -203, kz_nekoarc_Tail_003_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 119, -4, 0, kz_nekoarc_lLeg_001_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_nekoarc_lLeg_002_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -163, 0, kz_nekoarc_lLeg_002_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_nekoarc_lLeg_003_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 1, -246, 0, kz_nekoarc_lLeg_003_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -122, -4, 0, kz_nekoarc_rLeg_001_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_nekoarc_rLeg_002_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -2, -159, 0, kz_nekoarc_rLeg_002_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_nekoarc_rLeg_003_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -1, -250, 0, kz_nekoarc_rLeg_003_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kz_nekoarc_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, kz_nekoarc_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
