extern const GeoLayout bullet_bill_geo[];
extern Lights1 bullet_bill_eyes_f3d_lights;
extern Lights1 bullet_bill_mouth_f3d_lights;
extern u8 bullet_bill_eye_ci8[];
extern u8 bullet_bill_eye_ci8_pal_rgba16[];
extern u8 bullet_bill_teeth2_i8[];
extern Vtx bullet_bill_000_displaylist_mesh_layer_1_vtx_0[54];
extern Gfx bullet_bill_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx bullet_bill_000_displaylist_mesh_layer_1_vtx_1[46];
extern Gfx bullet_bill_000_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_bullet_bill_eyes_f3d[];
extern Gfx mat_revert_bullet_bill_eyes_f3d[];
extern Gfx mat_bullet_bill_mouth_f3d[];
extern Gfx bullet_bill_000_displaylist_mesh_layer_1[];
extern Gfx bullet_bill_material_revert_render_settings[];
