extern const GeoLayout boo_001_switch_opt1[];
extern const GeoLayout boo_geo[];
extern Lights1 boo_eyes_f3d_lights;
extern Lights1 boo_teeth_f3d_001_lights;
extern u8 boo_eyes_ci8[];
extern u8 boo_eyes_ci8_pal_rgba16[];
extern u8 boo_teeth_i8[];
extern Vtx boo_000_displaylist_mesh_layer_1_vtx_0[107];
extern Gfx boo_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx boo_000_displaylist_mesh_layer_1_vtx_1[15];
extern Gfx boo_000_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_boo_eyes_f3d[];
extern Gfx mat_revert_boo_eyes_f3d[];
extern Gfx mat_boo_teeth_f3d_001[];
extern Gfx boo_000_displaylist_mesh_layer_1[];
extern Gfx boo_material_revert_render_settings[];
