#include "src/game/envfx_snow.h"

const GeoLayout kitten_layla_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SCALE(LAYER_OPAQUE, 49152),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 81, 0, 0, -90, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kitten_layla_Root_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 31, 0, kitten_layla_Chest_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 32, 0, kitten_layla_Head_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 18, 30, 0, kitten_layla_lArm_001_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 44, 0, 0, kitten_layla_lArm_002_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 29, 0, 0, kitten_layla_lArm_003_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -18, 30, 0, kitten_layla_rArm_001_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -44, 0, 0, kitten_layla_rArm_002_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, -30, 0, 0, kitten_layla_rArm_003_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 14, -31, kitten_layla_Tail_001_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, kitten_layla_Tail_002_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, -34, kitten_layla_Tail_002_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, kitten_layla_Tail_003_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, -36, kitten_layla_Tail_003_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 16, 1, 0, kitten_layla_lLeg_001_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -26, 0, kitten_layla_lLeg_002_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -28, 0, kitten_layla_lLeg_003_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -15, 1, 0, kitten_layla_rLeg_001_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -26, 0, kitten_layla_rLeg_002_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -28, 0, kitten_layla_rLeg_003_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 6, 122, 0, 90, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kitten_layla_snowball_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 56, 0, kitten_layla_L_Head_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 29, -32, 65, kitten_layla_L_LFoot_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -27, -32, 66, kitten_layla_L_RFoot_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -12, -68, NULL),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, kitten_layla_L_Tail_002_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 1, 18, -29, kitten_layla_L_Tail_002_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, kitten_layla_L_Tail_003_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, -1, 28, -47, kitten_layla_L_Tail_003_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kitten_layla_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
