#ifndef SEQ_IDS_H
#define SEQ_IDS_H

// Sometimes a sequence id is represented as one of the below ids (the base id),
// optionally OR'd with SEQ_VARIATION.
// #define SEQ_BASE_ID 0xfe

#define SEQ_MENU_GAME_OVER (SEQ_MENU_TITLE_SCREEN)

enum SeqId {
    SEQ_SOUND_PLAYER,                 // 0x00
    SEQ_EVENT_CUTSCENE_COLLECT_STAR,  // 0x01
    SEQ_MENU_TITLE_SCREEN,            // 0x02; GOING UNUSED
    SEQ_LEVEL_GRASS,                  // 0x03 NEW_BOB
    SEQ_LEVEL_INSIDE_CASTLE,          // 0x04; NEW MIDI
    SEQ_LEVEL_WATER,                  // 0x05 NEW_JRB
    SEQ_LEVEL_HOT,                    // 0x06 NEW_LLL
    SEQ_LEVEL_BOSS_KOOPA,             // 0x07 EGGMAN1
    SEQ_LEVEL_SNOW,                   // 0x08 NEW_CCM
    SEQ_LEVEL_SLIDE,                  // 0x09 NEW_TTC
    SEQ_LEVEL_SPOOKY,                 // 0x0A NEW_BBH
    SEQ_EVENT_PIRANHA_PLANT,          // 0x0B
    SEQ_LEVEL_UNDERGROUND,            // 0x0C NEW_HMC
    SEQ_MENU_STAR_SELECT,             // 0x0D; NEW MIDI
    SEQ_EVENT_POWERUP,                // 0x0E; NEW MIDI
    SEQ_EVENT_METAL_CAP,              // 0x0F; NEW MIDI
    SEQ_EVENT_KOOPA_MESSAGE,          // 0x10; NEW MIDI
    SEQ_LEVEL_KOOPA_ROAD,             // 0x11 EGGSTAGE1
    SEQ_EVENT_HIGH_SCORE,             // 0x12; NEW_HIGHSCORE
    SEQ_EVENT_MERRY_GO_ROUND,         // 0x13 NEW_BBH2
    SEQ_EVENT_RACE,                   // 0x14
    SEQ_EVENT_CUTSCENE_STAR_SPAWN,    // 0x15; NEW MIDI
    SEQ_EVENT_BOSS,                   // 0x16; NEW BOSS
    SEQ_EVENT_CUTSCENE_COLLECT_KEY,   // 0x17
    SEQ_EVENT_ENDLESS_STAIRS,         // 0x18; NEW MIDI
    SEQ_LEVEL_BOSS_KOOPA_FINAL,       // 0x19 EGGMAN3
    SEQ_EVENT_CUTSCENE_CREDITS,       // 0x1A
    SEQ_EVENT_SOLVE_PUZZLE,           // 0x1B
    SEQ_EVENT_TOAD_MESSAGE,           // 0x1C
    SEQ_EVENT_PEACH_MESSAGE,          // 0x1D 
    SEQ_EVENT_CUTSCENE_INTRO,         // 0x1E
    SEQ_EVENT_CUTSCENE_VICTORY,       // 0x1F
    SEQ_EVENT_CUTSCENE_ENDING,        // 0x20; NEW MIDI
    SEQ_MENU_FILE_SELECT,             // 0x21; NEW MIDI
    SEQ_EVENT_CUTSCENE_LAKITU,        // 0x22 (not in JP)
    SEQ_LEVEL_NEW_WF,                 // 0x23 
    SEQ_LEVEL_NEW_LLL2,               // 0x24 LLL2
    SEQ_LEVEL_NEW_SSL,                // 0x25 NEW_SSL
    SEQ_LEVEL_NEW_SSL2,               // 0x26 SSL2
    SEQ_LEVEL_NEW_DDD,                // 0x27 SSL2
    SEQ_LEVEL_NEW_SL,                 // 0x28 SL
    SEQ_LEVEL_NEW_SL2,                // 0x29 SL2
    SEQ_LEVEL_NEW_WDW,                // 0x2A WDW
    SEQ_LEVEL_NEW_TTM,                // 0x2B TTM
    SEQ_LEVEL_NEW_TTM2,               // 0x2C TTM2
    SEQ_LEVEL_NEW_THI,                // 0x2D THI
    SEQ_LEVEL_NEW_RR,                 // 0x2E RR
    SEQ_LEVEL_EGGSTAGE2,              // 0x2F EGGSTAGE2
    SEQ_LEVEL_EGGMAN2,                // 0x30 EGGMAN2
    SEQ_LEVEL_EGGSTAGE3,              // 0x31 EGGSTAGE3
    SEQ_LEVEL_EGGMAN3FINALE,          // 0x32 EGGMAN3 FINALE
    SEQ_EVENT_BOSS_WISEMAN,           // 0x33 WISEMAN
    SEQ_MISSION_STREET,               // 0x34 MISSION STREET
    SEQ_KARAOKE_BAR,                  // 0x35 KARAOKE BAR
    SEQ_WHITE_PARK,                   // 0x36 WHITE PARK
    SEQ_NTMFUGIYAMA,                  // 0x37 FUGIYAMA GOLF CLUB
    SEQ_NTM_STARGET,                  // 0x38 FUGIYAMA GOLF CLUB - STAR GET
    SEQ_RACING,                       // 0x39 VS GEMERL/TAILS
    SEQ_SHELLSLIDE,                   // 0x3A VS SHELL SLIDING
    SEQ_PSS_LEAFFOREST,               // 0x3B VS PSS - LEAF FOREST BETA
    SEQ_THEEND,                       // 0x3C VS THE END
    SEQ_EVENT_VANISH,                 // 0x3D VANISH CAP
    SEQ_EVENT_PEACH_MESSAGE_ORI,      // 0x3E ORIGINAL PEACH MESSAGE
    SEQ_EVENT_HIGH_SCORE2,            // 0x3F; NEW_HIGHSCORE2
    SEQ_EVENT_HIGH_SCORE3,            // 0x40; NEW_HIGHSCORE3
    SEQ_EVENT_HIGH_SCORE4,            // 0x41; NEW_HIGHSCORE3
    SEQ_EVENT_HIGH_SCORE5,            // 0x42; NEW_HIGHSCORE3
    SEQ_DDRTRACK1,                    // 0x43; DDR TRACK1
    SEQ_DDRTRACK2,                    // 0x44; DDR TRACK2
    SEQ_BMTRACK1,                     // 0x45; BM TRACK1
    SEQ_LEVEL_NEW_TOTWC,              // 0x46; TOTWC
    SEQ_LEVEL_NEW_COTMC,              // 0x47; COTMC
    SEQ_LEVEL_EGGMAN3FINALE_END,      // 0x48; EGGMAN3 FINALE END
    SEQ_COLLECT_STAR_TF2,             // 0x49; COLLECT STAR (FOR ENGINEER)
    SEQ_COLLECT_STAR_CV,              // 0x4A; COLLECT STAR (FOR MARIA)
    SEQ_COLLECT_STAR_ROLL,            // 0x4B; COLLECT STAR (FOR ROLL)
    SEQ_COLLECT_STAR_MARIO,           // 0x4C; COLLECT STAR (FOR MARIO)
    SEQ_COLLECT_STAR_DAWN,            // 0x4D; COLLECT STAR (FOR DAWN)
    SEQ_COLLECT_STAR_SERENA,          // 0x4E; COLLECT STAR (FOR SERENA)
    SEQ_COLLECT_STAR_DUDLEY,          // 0x4F; COLLECT STAR (FOR DUDLEY)
    SEQ_COLLECT_STAR_KATALINA,        // 0x50; COLLECT STAR (FOR KATALINA)
    SEQ_COLLECT_STAR_SORA,            // 0x51; COLLECT STAR (FOR SORA)
    SEQ_COLLECT_STAR_LAYLA,           // 0x52; COLLECT STAR (FOR LAYLA)
    SEQ_COLLECT_STAR_SWEET,           // 0x53; COLLECT STAR (FOR SWEET/ICHIBAN)
    SEQ_COLLECT_STAR_MMX,             // 0x54; COLLECT STAR (FOR MMX)
    SEQ_COLLECT_STAR_DANI,            // 0x55; COLLECT STAR (FOR DANI)
    SEQ_COLLECT_STAR_JHW,             // 0x56; COLLECT STAR (FOR JOHNNY/GOKU/PAN)
    SEQ_COLLECT_STAR_CAROLINE,        // 0x57; COLLECT STAR (FOR CAROLINE)
    SEQ_COLLECT_STAR_BAIT,            // 0x58; COLLECT STAR (FOR BAIT)
    SEQ_COLLECT_STAR_CHEF,            // 0x59; COLLECT STAR (FOR CHEF)
    SEQ_COLLECT_STAR_KITTEN,          // 0x5A; COLLECT STAR (FOR KITTEN/TAILS)
    SEQ_COLLECT_STAR_VAL,             // 0x5B; COLLECT STAR (FOR VAL)
    SEQ_COLLECT_STAR_LATINA,          // 0x5C; COLLECT STAR (FOR LATINA)
    SEQ_COLLECT_STAR_MACER,           // 0x5D; COLLECT STAR (FOR MACER)
    SEQ_COLLECT_STAR_WONDER,          // 0x5E; COLLECT STAR (FOR WONDER)
    SEQ_COLLECT_STAR_LAN,             // 0x5F; COLLECT STAR (FOR LAN)
    SEQ_COLLECT_STAR_KZ,              // 0x60; COLLECT STAR (FOR KZ)
    SEQ_COLLECT_STAR_CREAMOCCHIA,     // 0x61; COLLECT STAR (FOR CREAMOCCHIA)
    SEQ_COLLECT_STAR_JACK,            // 0x62; COLLECT STAR (FOR JACK)
    SEQ_COLLECT_STAR_VERGIL,          // 0x63; COLLECT STAR (FOR VERGIL)
    SEQ_COLLECT_STAR_POCKY,           // 0x64; COLLECT STAR (FOR POCKY)
    SEQ_COLLECT_STAR_MAGE,            // 0x65; COLLECT STAR (FOR MAGE)
    SEQ_COLLECT_STAR_KATE,            // 0x66; COLLECT STAR (FOR KATE)
    SEQ_COLLECT_STAR_DOT,             // 0x67; COLLECT STAR (FOR DOT)
    SEQ_COLLECT_STAR_TRAVIS,          // 0x68; COLLECT STAR (FOR TRAVIS)
    SEQ_COLLECT_STAR_KLONOA,          // 0x69; COLLECT STAR (FOR KLONOA)
    SEQ_COLLECT_STAR_AUSTIN,          // 0x6A; COLLECT STAR (FOR AUSTIN)
    SEQ_COLLECT_STAR_SENA,            // 0x6B; COLLECT STAR (FOR SENA)
    SEQ_BMTRACK2,                     // 0x6C; BM TRACK2
    SEQ_COLLECT_STAR_DRUMMER,         // 0x6D; COLLECT STAR (FOR DRUMMER)
    SEQ_COLLECT_STAR_AMY,             // 0x6E; COLLECT STAR (FOR AMY)
    SEQ_COLLECT_STAR_RIDERS,          // 0x6F; COLLECT STAR (FOR RIDERS)
    SEQ_COLLECT_STAR_WINTER,          // 0x70; COLLECT STAR (FOR WINTER)
    SEQ_COLLECT_STAR_SPRING,          // 0x71; COLLECT STAR (FOR SPRING)
    SEQ_COLLECT_STAR_UNICORN,         // 0x72; COLLECT STAR (FOR UNICORN)
    SEQ_COLLECT_STAR_YUKATA,          // 0x73; COLLECT STAR (FOR YUKATA)
    SEQ_COLLECT_STAR_SWIMSUIT,        // 0x74; COLLECT STAR (FOR SWIMSUIT)
    SEQ_COLLECT_STAR_GOEMON,          // 0x75; COLLECT STAR (FOR GOEMON)
    SEQ_COLLECT_STAR_SHADOW,          // 0x76; COLLECT STAR (FOR SHADOW)
    SEQ_COLLECT_STAR_TIKAL,           // 0x77; COLLECT STAR (FOR TIKAL)
    SEQ_COLLECT_STAR_DETECTIVE,       // 0x78; COLLECT STAR (FOR DETECTIVE)
    SEQ_COLLECT_STAR_PRINCESS,        // 0x79; COLLECT STAR (FOR PRINCESS)
    SEQ_COLLECT_STAR_MIKU,            // 0x7A; COLLECT STAR (FOR MIKU)
    SEQ_COLLECT_STAR_LUNAR,           // 0x7B; COLLECT STAR (FOR MIKU)
    SEQ_COLLECT_STAR_BLAZE,           // 0x7C; COLLECT STAR (FOR BLAZE)
    SEQ_COLLECT_STAR_MARINE,          // 0x7D; COLLECT STAR (FOR MARINE)
    SEQ_COLLECT_STAR_SILVER,          // 0x7E; COLLECT STAR (FOR SILVER)
    SEQ_COLLECT_STAR_CHARMY,          // 0x7F; COLLECT STAR (FOR CHARMY)
    SEQ_COLLECT_STAR_COSMO,           // 0x80; COLLECT STAR (FOR COSMO)
    SEQ_COUNT 
};

#endif // SEQ_IDS_H
