#include "src/game/envfx_snow.h"

const GeoLayout cheese_follow_anya_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 0, 80),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_OPAQUE, 14418),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_ALPHA, 0, 168, 0, cheese_follow_anya_Root_mesh_layer_4),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, cheese_follow_anya_Root_mesh_layer_1),
					GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 48, 0, cheese_follow_anya_Head_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, cheese_follow_anya_Head_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 25, 35, -62, cheese_follow_anya_LWing_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, -26, 35, -62, cheese_follow_anya_RWing_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, -56, 46, 0, cheese_follow_anya_lArm_001_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, -47, -44, 0, cheese_follow_anya_lLeg_001_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, 58, 46, 0, cheese_follow_anya_rArm_001_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, 46, -44, 0, cheese_follow_anya_rLeg_001_mesh_layer_4),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, cheese_follow_anya_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, cheese_follow_anya_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
