#include "src/game/envfx_snow.h"

const GeoLayout jack_Head_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 211, 0, jack_Head_mesh_layer_1_mat_override_jack_eyes2_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, jack_Head_mesh_layer_4_mat_override_jack_eyes2_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout jack_Head_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 211, 0, jack_Head_mesh_layer_1_mat_override_jack_eyes3_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, jack_Head_mesh_layer_4_mat_override_jack_eyes3_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout jack_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 204, 80),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_OPAQUE, 9175),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_ALPHA, 0, 385, 0, jack_Root_mesh_layer_4),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, jack_Root_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 154, 0, jack_Chest_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, jack_Chest_mesh_layer_1),
						GEO_SWITCH_CASE(0, geo_switch_npc_face),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 211, 0, jack_Head_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_ALPHA, jack_Head_mesh_layer_4),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, jack_Head_Switch_opt1),
							GEO_BRANCH(1, jack_Head_Switch_opt2),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, 88, 140, 0, jack_lArm_001_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 215, 0, 0, jack_lArm_002_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_ALPHA, 166, 0, 0, jack_lArm_003_mesh_layer_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, -88, 140, 0, jack_rArm_001_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, -208, 0, 0, jack_rArm_002_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_ALPHA, -162, 0, 0, jack_rArm_003_mesh_layer_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 54, 18, 0, jack_lLeg_001_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, -5, -237, 0, jack_lLeg_002_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 12, -236, 0, jack_lLeg_003_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, -52, 18, 0, jack_rLeg_001_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_ALPHA, 6, -236, 0, jack_rLeg_002_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, -8, -238, 0, jack_rLeg_003_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, jack_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, jack_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
